### ISSUE TITLE
noarch package may need to be removed.

### ISSUE THREAD

**Issue by gigony** [conda-forge/openslide-python-feedstock#4]
Since openslide-python package has platform-specific library file (such as `_convert.cpython-39-x86_64-linux-gnu.so`), `noarch` package cannot work in Windows(See https://github.com/openslide/openslide-python/issues/124).

In addition to that, in `noarch` package, it has `_convert.cpython-39-x86_64-linux-gnu.so` which works only for 64-bit linux CPython 3.9.
(See https://anaconda.org/conda-forge/openslide-python/files).

I have Python 3.8 on Linux and when I install `openslide-python`, it installs `noarch` package so see the following message as it doesn't have `_convert.cpython-38-x86_64-linux-gnu.so`.

```bash
>>> import openslide
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gbae/miniconda3/envs/cucim-openslide/lib/python3.8/site-packages/openslide/__init__.py", line 35, in <module>
    from openslide import lowlevel
  File "/home/gbae/miniconda3/envs/cucim-openslide/lib/python3.8/site-packages/openslide/lowlevel.py", line 40, in <module>
    from . import _convert
ImportError: cannot import name '_convert' from partially initialized module 'openslide' (most likely due to a circular import) (/home/gbae/miniconda3/envs/cucim-openslide/lib/python3.8/site-packages/openslide/__init__.py)
>>> exit()
```

Workaround is:
`conda install conda-forge/linux-64::openslide-python`

Another question is whether if Windows version of this package would be available in the future (I don't need it but other users may want it to install on Windows).

- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at /home/gbae/miniconda3/envs/openslide:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
ca-certificates           2021.5.30            ha878542_0    conda-forge
cairo                     1.16.0            h6cf1ce9_1008    conda-forge
certifi                   2021.5.30        py38h578d9bd_0    conda-forge
cudatoolkit               11.2.2               he111cf0_8    conda-forge
fontconfig                2.13.1            hba837de_1005    conda-forge
freetype                  2.10.4               h0708190_1    conda-forge
gdk-pixbuf                2.42.6               h04a7f16_0    conda-forge
gettext                   0.19.8.1          h0b5b191_1005    conda-forge
glib                      2.68.3               h9c3ff4c_0    conda-forge
glib-tools                2.68.3               h9c3ff4c_0    conda-forge
icu                       68.1                 h58526e2_0    conda-forge
jbig                      2.1               h7f98852_2003    conda-forge
jpeg                      9d                   h36c2ea0_0    conda-forge
lcms2                     2.12                 hddcbb42_0    conda-forge
ld_impl_linux-64          2.36.1               hea4e1c9_0    conda-forge
lerc                      2.2.1                h9c3ff4c_0    conda-forge
libdeflate                1.7                  h7f98852_5    conda-forge
libffi                    3.3                  h58526e2_2    conda-forge
libgcc-ng                 9.3.0               h2828fa1_19    conda-forge
libglib                   2.68.3               h3e27bee_0    conda-forge
libgomp                   9.3.0               h2828fa1_19    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
libpng                    1.6.37               h21135ba_2    conda-forge
libstdcxx-ng              9.3.0               h6de172a_19    conda-forge
libtiff                   4.3.0                hf544144_1    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libwebp-base              1.2.0                h7f98852_2    conda-forge
libxcb                    1.13              h7f98852_1003    conda-forge
libxml2                   2.9.12               h72842e0_0    conda-forge
lz4-c                     1.9.3                h9c3ff4c_0    conda-forge
ncurses                   6.2                  h58526e2_4    conda-forge
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openjpeg                  2.4.0                hb52868f_1    conda-forge
openslide                 3.4.1                h978ee9a_4    conda-forge
openslide-python          1.1.2              pyh4b9e410_2    conda-forge
openssl                   1.1.1k               h7f98852_0    conda-forge
pcre                      8.45                 h9c3ff4c_0    conda-forge
pillow                    8.2.0            py38ha0e1e83_1    conda-forge
pip                       21.1.3             pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               h36c2ea0_0    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
python                    3.8.10          h49503c6_1_cpython    conda-forge
python_abi                3.8                      2_cp38    conda-forge
readline                  8.1                  h46c0cb4_0    conda-forge
setuptools                49.6.0           py38h578d9bd_3    conda-forge
sqlite                    3.36.0               h9cd32fc_0    conda-forge
tk                        8.6.10               h21135ba_1    conda-forge
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libice               1.0.10               h7f98852_0    conda-forge
xorg-libsm                1.2.3             hd9c2040_1000    conda-forge
xorg-libx11               1.7.2                h7f98852_0    conda-forge
xorg-libxau               1.0.9                h7f98852_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xorg-libxext              1.3.4                h7f98852_1    conda-forge
xorg-libxrender           0.9.10            h7f98852_1003    conda-forge
xorg-renderproto          0.11.1            h7f98852_1002    conda-forge
xorg-xextproto            7.3.0             h7f98852_1002    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
zlib                      1.2.11            h516909a_1010    conda-forge
zstd                      1.5.0                ha95c52a_0    conda-forge
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
    active environment : openslide
    active env location : /home/gbae/miniconda3/envs/openslide
            shell level : 1
       user config file : /home/gbae/.condarc
 populated config files : /home/gbae/.condarc
          conda version : 4.10.1
    conda-build version : 3.21.4
         python version : 3.8.5.final.0
       virtual packages : __linux=5.10.16.3=0
                          __glibc=2.31=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/gbae/miniconda3  (writable)
      conda av data dir : /home/gbae/miniconda3/etc/conda
  conda av metadata url : https://repo.anaconda.com/pkgs/main
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/gbae/miniconda3/pkgs
                          /home/gbae/.conda/pkgs
       envs directories : /home/gbae/miniconda3/envs
                          /home/gbae/.conda/envs
               platform : linux-64
             user-agent : conda/4.10.1 requests/2.25.1 CPython/3.8.5 Linux/5.10.16.3-microsoft-standard-WSL2 ubuntu/20.04.1 glibc/2.31
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```
</details>

**Comment by sarthakpati** [comment]
I agree - if the [openslide](https://anaconda.org/conda-forge/openslide) recipe can be updated to build Windows, this can be used for this recipe, too. Could you please put in a PR to remove this?

**Comment by jakirkham** [comment]
Submitted PR ( https://github.com/conda-forge/admin-requests/pull/323 ) to mark the `noarch` packages `broken` to ensure users don't pick these up accidentally
